import json

from web3 import Web3

from solcx import compile_standard, install_solc
import os
from dotenv import load_dotenv

# Connecting with out local ganache private key
# For security reasons, the .env file storing private key is not added to git
# personal private key can be generated by using the software "ganache"
# To use that private key, create a file named .env and store
# export PRIVATE_KEY=<Your Private Key>
# the load_dotenv function below will load that private key into the code
load_dotenv()
